### ISSUE TITLE
Encontro #5

### ISSUE THREAD

**Issue by fczuardi-luizalabs** [Rust-dojo/eventos#11]
- [x] flyer: https://user-images.githubusercontent.com/77620604/197524069-e7ac18dc-66ca-4428-8032-57e5b1a7a901.png
- [x] evento no LinkedIn: - https://www.linkedin.com/posts/fabricio_rust-rustlang-coding-activity-6987757969245417472-xD_1/
- [x] lembrete na mailing list: https://groups.io/g/rust-dojo/message/2
- [x] lembretes no twitter
  - fczuardi: https://twitter.com/fczuardi/status/1584513320992010240
- [x] lembretes no Slack:
  - #random: https://luizalabs.slack.com/archives/C024FR432/p1666613677929709

**Comment by fczuardi-luizalabs** [comment]
![Rust para Iniciantes](https://user-images.githubusercontent.com/77620604/197524069-e7ac18dc-66ca-4428-8032-57e5b1a7a901.png)

**Comment by fczuardi** [comment]
https://groups.io/g/rust-dojo/message/2
